name: dist-s1-harness
channels:
  - conda-forge
dependencies:
  - python=>3.11 # required for shapely 2.0.0
  - flake8
  - backoff
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - jupyter
  - contextily
  - boto3
  - ipykernel
  - rasterio
  - geopandas
  - shapely=>2.0
  - pandas
  - tqdm
  - requests
  - rasterio
  - asf_search
  - dill
  - astropy
  - backoff
  - papermill
  - mpire
  - multiprocess
  - pyarrow
  - pip:
    - git+https://github.com/OPERA-Cal-Val/distmetrics.git
